images:
  image:
    repository: ghcr.io/sausin/outpost-ts
    tag: 0.4.0
  redis_image:
    repository: valkey/valkey
    tag: 9.1.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  outpost_container_name: outpost
  redis_container_name: outpost-redis
  perms_container_name: outpost-perms
  config_path: /config
